# Generated by Django 3.2.9 on 2021-11-29 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_criollo', models.CharField(max_length=255)),
                ('nombre_comun', models.CharField(max_length=255)),
                ('nombre_propio', models.CharField(max_length=255)),
                ('edad', models.CharField(max_length=255)),
                ('procedencia', models.CharField(max_length=255)),
                ('fecha_recepcion', models.DateField()),
                ('sexo', models.CharField(max_length=20)),
                ('estado_salud', models.CharField(max_length=255)),
                ('detalles_salud', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('ruta', models.CharField(help_text='Direccion del archivo', max_length=255, primary_key=True, serialize=False)),
                ('peso', models.CharField(help_text='Peso del archivo', max_length=255)),
                ('nombre', models.CharField(help_text='Nombre del archivo', max_length=255)),
                ('creado', models.DateField(help_text='Fecha de cracion del archivo')),
                ('tipo', models.CharField(help_text='Extension del archivo para saber su tipo', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('ci', models.CharField(help_text='Cedula de indentidad del trabajador', max_length=15, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(help_text='Razon social del trabajador', max_length=255)),
                ('domicilio', models.CharField(help_text='Direccion de domicilio del trabajador', max_length=255)),
                ('telefono', models.CharField(help_text='Numero de telefono del trabajador', max_length=255)),
                ('email', models.CharField(help_text='Direccion de correo electronico del trabajador', max_length=255)),
                ('nombre', models.CharField(help_text='Nombre del trabajador', max_length=255)),
                ('root', models.BooleanField(help_text='0 si es un trabajador normal, 1 si es super usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomia',
            fields=[
                ('especie', models.CharField(help_text='Especie del animal', max_length=255, primary_key=True, serialize=False)),
                ('familia', models.CharField(help_text='Familia del animal', max_length=255)),
                ('orden', models.CharField(help_text='Orden del animal', max_length=255)),
                ('genero', models.CharField(help_text='Genero del animal', max_length=255)),
                ('subespecie', models.CharField(help_text='Subespecie del animal', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_acta_decomiso', models.IntegerField()),
                ('fecha_registro', models.DateField()),
                ('CCFS', models.CharField(max_length=255)),
                ('modalidad_funcionamiento', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('lugar_exposicion', models.CharField(max_length=255)),
                ('motivo_recepcion', models.CharField(max_length=255)),
                ('autorizado_por', models.CharField(max_length=255)),
                ('nro_acta_traslado', models.IntegerField()),
                ('nro_MMAA', models.IntegerField()),
                ('ci_recibido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.operador')),
                ('id_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Microchip',
            fields=[
                ('nro', models.IntegerField(help_text='Numero unico del microchip.', primary_key=True, serialize=False)),
                ('fecha', models.DateField(help_text='Fecha de registro del microchip')),
                ('peso', models.IntegerField()),
                ('tamano', models.IntegerField()),
                ('caracteristicas_fenotipicas', models.TextField()),
                ('datos_vacunacion', models.TextField()),
                ('observaciones', models.TextField()),
                ('ci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.operador')),
            ],
        ),
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_deceso', models.DateField()),
                ('CCFS', models.CharField(max_length=255)),
                ('modalidad_funcionamiento', models.CharField(max_length=255)),
                ('nombre_guarda_fauna', models.CharField(max_length=255)),
                ('nombre_veterinario', models.CharField(max_length=255)),
                ('nombre_director', models.CharField(max_length=255)),
                ('nro_MMAA', models.IntegerField()),
                ('motivo_salida', models.TextField()),
                ('causa_deceso', models.TextField()),
                ('lesiones', models.TextField()),
                ('diagnostico_deceso', models.TextField()),
                ('ci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.operador')),
                ('direccion_archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.archivo')),
                ('id_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='cod_int',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.microchip'),
        ),
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.taxonomia'),
        ),
        migrations.AddField(
            model_name='animal',
            name='ruta_archivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.archivo'),
        ),
    ]
