# Generated by Django 3.2.9 on 2021-11-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20211130_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='autorizado',
            field=models.BooleanField(help_text='0 si no esta autorizado, 1 si esta autorizado'),
            preserve_default=False,
        ),
    ]
