# Generated by Django 3.2.9 on 2021-12-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_operador_autorizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='apellido',
            field=models.CharField(help_text='Apellido del trabajador', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operador',
            name='password',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
