# Generated by Django 3.2.9 on 2021-12-06 04:09

import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20211204_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=db.models.upload_path),
        ),
    ]
