# Generated by Django 3.2.9 on 2021-12-07 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_archivo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='baja',
            name='direccion_archivo_laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laboratorio', to='db.archivo'),
        ),
        migrations.AlterField(
            model_name='baja',
            name='direccion_archivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forense', to='db.archivo'),
        ),
    ]
