# Generated by Django 3.2.9 on 2021-12-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20211207_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='vivo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
